I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/r_Aaabbaa.rpy", line 5, in script
    kouji "そうだね。"
Exception: Sayer 'kouji' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/r_Aaabbaa.rpy", line 5, in script
    kouji "そうだね。"
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'kouji' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.1.24090601
VisualNovel_Programming 1.0
Mon Jan 27 19:39:07 2025
